Awx/22.5.0
Websoft9/docker-library pull request #305
Opened 2023-07-29 12:01 UTC by huabingli

修复ALLOWED_HOSTS错误
修改CSRF跨域问题
代码规范

2023-07-31 01:41 UTC, chendelin1982 requested changes
安装方案的出处？请在Notes中说明，并提供每一个关键点的来源

2023-07-31 03:50 UTC, laozhou0731 commented
方案验证失败：
按文档[AWX 使用入门](https://support.websoft9.com/docs/awx#awx-%E4%BD%BF%E7%94%A8%E5%85%A5%E9%97%A8）验证失败，从 GitHub  / gitee 拉取案例失败
![image](https://github.com/Websoft9/docker-library/assets/62225175/032a6382-552f-46de-8b6d-628f971dbd59)

2023-07-31 17:08 UTC, huabingli commented
@laozhou0731 问题已修复，镜像中找不到ansible-runner命令导致，重新编写Dockerfile文件安装ansible-runnner和ansible解决问题

2023-07-31 17:09 UTC, huabingli commented
@chendelin1982 安装方案的出处，关键点的来源，已在Notes中说明。

2023-08-01 06:05 UTC, chendelin1982 commented
> @laozhou0731 问题已修复，镜像中找不到ansible-runner命令导致，重新编写Dockerfile文件安装ansible-runnner和ansible解决问题

Good

2023-08-01 06:43 UTC, huabingli commented
Dockerfile文件是根据[Dockerfile.j2](https://github.com/ansible/awx/blob/devel/tools/ansible/roles/dockerfile/templates/Dockerfile.j2)对[quay.io/ansible/awx](https://quay.io/repository/ansible/awx/manifest/sha256:64a95fa73f203c7b92ea97043b170e48b1a3fb1b24bc6386b76d39edace922e7)镜像的修改。

2023-08-01 08:18 UTC, merged